# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db637fb33af61b2108a422fb277b44f8b4023170c7b39e18224b76a2845afef02106472d91cc6ef86e4abe805b71146062001ed4be701a49b4c91849a90eb4fa

test:
  secret_key_base: 2642a0798b5c79ef12ca93cfe1969cf65588ef08e1dfa67d45160bca030798cfeca00bc7c0763c38232f23d7bae418d85d823af1c2dee5ffd8d39755df557890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
